from database.database import Base
from sqlalchemy import Column, ForeignKey, Integer, String, Time, BigInteger, Text, DOUBLE_PRECISION, TIMESTAMP, \
    SmallInteger
from sqlalchemy.sql import func


class Venues(Base):
    __tablename__ = 'mft_venues'

    id = Column(BigInteger, primary_key=True, index=True)
    lang = Column(String(5), default='en', nullable=False)
    sub_category_id = Column(BigInteger, nullable=False)
    status = Column(BigInteger, default=0, nullable=False)
    assign_featured = Column(BigInteger, default=0, nullable=False)
    reservation = Column(BigInteger, default=0, nullable=False)
    slug = Column(String(191), nullable=False)
    venue_capacity = Column(BigInteger)
    lat = Column(Text)
    long = Column(Text)
    location = Column(Text)
    country = Column(String(191))
    city = Column(String(191))
    area = Column(String(191))
    start_date_time = Column(TIMESTAMP(timezone=True))
    end_date_time = Column(TIMESTAMP(timezone=True))
    cusine_name = Column(Text)
    view_floor_plan = Column(Text)
    city_id = Column(BigInteger, default=0)
    images = Column(Text)
    feature_image = Column(Text)
    icon = Column(Text)
    video = Column(Text)
    amenity_id = Column(Text)
    landmark_id = Column(Text)
    whatsapp = Column(String(191))
    contact = Column(String(191))
    email = Column(String(191))
    created_at = Column(TIMESTAMP(timezone=True), server_default=func.now())
    updated_at = Column(TIMESTAMP(timezone=True), onupdate=func.now())
    start_time = Column(Time(timezone=False))
    end_time = Column(Time(timezone=False))
    dynamic_main_ids = Column(Text)
    dynamic_sub_ids = Column(Text)
    prices = Column(Text)
    view_menu = Column(Text)
    youtube_img = Column(BigInteger)
    map_review = Column(BigInteger)
    map_rating = Column(DOUBLE_PRECISION)
    created_by = Column(BigInteger, default=1, nullable=False)
    is_publisher = Column(BigInteger, default=0, nullable=False)
    meta_img_alt = Column(Text)
    meta_img_title = Column(Text)
    meta_img_description = Column(Text)
    stories = Column(Text)
    is_popular = Column(BigInteger, default=0, nullable=False)
    is_hot = Column(SmallInteger, default=0, nullable=False)
    is_trending = Column(SmallInteger, default=0, nullable=False)
    is_verified = Column(SmallInteger, default=0)
    opening_hours = Column(Text)
    discount_offer = Column(DOUBLE_PRECISION, default=0, nullable=False)
    keywords = Column(String(2000), default='[]', nullable=False)
    deleted_at = Column(TIMESTAMP(timezone=True))
    title = Column(Text, nullable=False)
    views = Column(BigInteger, default=0, nullable=False)
    description = Column(Text, nullable=False)
    is_draft = Column(BigInteger, default=0, nullable=False)
    meta_title = Column(Text)
    meta_description = Column(Text)
    meta_tags = Column(Text)
    status_text = Column(Text)
